allowBuilds:
  '@firebase/util': true
  '@prisma/engines': true
  cpu-features: true
  prisma: true
  protobufjs: true
  ssh2: true
onlyBuiltDependencies:
  - "@firebase/util"
  - "@prisma/engines"
  - cpu-features
  - prisma
  - protobufjs
  - ssh2
